use crate::models::{TermiusHost, TermiusIdentity, TermiusKey, TermiusVault};
use anyhow::Result;
use std::collections::HashMap;

/// Generates a standard ~/.ssh/config file content
pub fn generate_ssh_config(vault: &TermiusVault, keys_dir_name: &str) -> String {
    let mut out = String::new();
    out.push_str("# =========================================================\n");
    out.push_str("# Generated by Termius Vault Backup Exporter\n");
    out.push_str(&format!("# Timestamp: {}\n", vault.export_timestamp));
    out.push_str("# =========================================================\n\n");

    let keys_by_id: HashMap<&str, &TermiusKey> = vault.keys.iter().map(|k| (k.id.as_str(), k)).collect();
    let identities_by_id: HashMap<&str, &TermiusIdentity> = vault.identities.iter().map(|i| (i.id.as_str(), i)).collect();

    for host in &vault.hosts {
        let clean_alias = sanitize_filename(&host.label);
        out.push_str(&format!("Host {}\n", clean_alias));
        out.push_str(&format!("    HostName {}\n", host.address));

        if let Some(port) = host.port {
            if port != 22 {
                out.push_str(&format!("    Port {}\n", port));
            }
        }

        // Determine user (from host or linked identity)
        let username = host.username.as_deref().or_else(|| {
            host.identity_id.as_deref().and_then(|id_id| {
                identities_by_id.get(id_id).and_then(|ident| ident.username.as_deref())
            })
        });

        if let Some(user) = username {
            if !user.is_empty() {
                out.push_str(&format!("    User {}\n", user));
            }
        }

        // Determine linked key
        let key_id = host.key_id.as_deref().or_else(|| {
            host.identity_id.as_deref().and_then(|id_id| {
                identities_by_id.get(id_id).and_then(|ident| ident.key_id.as_deref())
            })
        });

        if let Some(kid) = key_id {
            if let Some(key) = keys_by_id.get(kid) {
                let key_filename = format!("{}.pem", sanitize_filename(&key.label));
                out.push_str(&format!("    IdentityFile {}/{}\n", keys_dir_name, key_filename));
                out.push_str("    IdentitiesOnly yes\n");
            }
        }

        if let Some(comment) = &host.comment {
            if !comment.is_empty() {
                out.push_str(&format!("    # Comment: {}\n", comment.replace('\n', " ")));
            }
        }

        out.push('\n');
    }

    out
}

/// Generates CSV format for all hosts
pub fn generate_hosts_csv(vault: &TermiusVault) -> Result<String> {
    let mut wtr = csv::Writer::from_writer(vec![]);

    // Header
    wtr.write_record(&["Label", "Address", "Port", "User", "Key_Label", "Tags", "Comment"])?;

    let keys_by_id: HashMap<&str, &TermiusKey> = vault.keys.iter().map(|k| (k.id.as_str(), k)).collect();
    let identities_by_id: HashMap<&str, &TermiusIdentity> = vault.identities.iter().map(|i| (i.id.as_str(), i)).collect();

    for host in &vault.hosts {
        let username = host.username.as_deref().unwrap_or_else(|| {
            host.identity_id.as_deref().and_then(|id_id| {
                identities_by_id.get(id_id).and_then(|ident| ident.username.as_deref())
            }).unwrap_or("")
        });

        let key_id = host.key_id.as_deref().or_else(|| {
            host.identity_id.as_deref().and_then(|id_id| {
                identities_by_id.get(id_id).and_then(|ident| ident.key_id.as_deref())
            })
        });

        let key_label = key_id.and_then(|kid| keys_by_id.get(kid)).map(|k| k.label.as_str()).unwrap_or("");
        let tags_str = host.tags.join("; ");
        let port_str = host.port.map(|p| p.to_string()).unwrap_or_else(|| "22".to_string());

        wtr.write_record(&[
            &host.label,
            &host.address,
            &port_str,
            username,
            key_label,
            &tags_str,
            host.comment.as_deref().unwrap_or(""),
        ])?;
    }

    let csv_data = String::from_utf8(wtr.into_inner()?)?;
    Ok(csv_data)
}

pub fn sanitize_filename(name: &str) -> String {
    name.chars()
        .map(|c| if c.is_alphanumeric() || c == '-' || c == '_' || c == '.' { c } else { '_' })
        .collect()
}
